display:
  mach: 3
  unit:
    name: "mph"
    factor: 2.23694
quarkus:
  http:
    port: 9091
  log:
    console:
      json:
        pretty-print: true
        date-format: "YYYY-MM-dd HH:mm:ss"
        exception-output-type: "detailed-and-formatted"
